### ISSUE TITLE
Percentage not working

### ISSUE THREAD

**Issue by CaptainAlienHD** [ConnorLinfoot/CratesPlus#120]
Spigot version: 1.8.8
CratesPlus version: 3.1.7
Issue: There is no Percentage/chances option in config file, when you create Crate for first time using /crate create and reopen config you are seeing "percentage" line in config but when you use for example more items that "example sword" using /crate settings - Percentage is automatic removed and no working in config even when you try to add it manually whole plugin is bugging.
Config Pastebin: http://pastebin.com/VXjc7sW1

**Comment by CaptDarkStar** [comment]
If you are adding items via the GUI in game, the config generation does not include the percentage variable. Not sure if this is by design or not. You have to add the variable under the item data variable and it will work perfectly. If you do add percentages, you have to make sure that all the items add up to exactly 100%. If all the items add up over (or under) 100%, they will not work at all. Also keep in mind that currently there is no support for decimals in the percentages.

**Comment by CaptainAlienHD** [comment]
So it is possible for example to add all items with GUI in selected chest's and then just to add Percentage to every items in config? it will work?

**Comment by ConnorLinfoot** [comment]
Yes you have to add it yourself to the config file, it's not automatic.
