### ISSUE TITLE
Kits in crates

### ISSUE THREAD

**Issue by Bjezirds** [ConnorLinfoot/CratesPlus#122]
Is there anyway you could put like a kit in a crate? so when a player get it they get the whole kit package

**Comment by CaptDarkStar** [comment]
Yes, this is very easily done. You just have to setup the item in the config yourself as a command instead of an item. Here is an example: https://gyazo.com/c80d0f0b68052d461422730a121b80e7

Just change "spawner give %name% spider" to whatever command you want. In this case you would want something like "kit nameofkit %name%"
