### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by computernerd10** [ConnorLinfoot/CratesPlus#182]
Hello there!
We recently installed CratesPlus and set it up, however I found out that if you are not opped you can not open the crate even with the key. Do you know why this is happening and how to fix it?

We have World Guard, which may or may not effect it.

**Comment by LPGamersRob** [comment]
have you tried placing the crates outside the worldguarded area ?

there seems to be a big problem when it comes to this and no one has come up with the solution to why they both react badly.

**Comment by computernerd10** [comment]
We have a __global__ region.

**Comment by LPGamersRob** [comment]
yeah my server had a global region an nowhere i placed a crate it did not work,

i have moved from this plugin because for the last week i have looked around and tried a lot of things to stop the conflict but can not seen to resolve this, until this is implemented i am going to leave this where it stands

**Comment by ConnorLinfoot** [comment]
The plugin uses interact to detect when a player clicks a crate. I'm personally not familiar with WorldGuard but if there is any flag for interact that's probably the best thing to try.
