### ISSUE TITLE
Hologram text isbt working + Config resets?

### ISSUE THREAD

**Issue by hoopzah** [ConnorLinfoot/CratesPlus#257]
There is no hologram text above the rates showing which is which, and my config keeps resetting. i know it tells me how to fix but i didn't quite understand what output to put it to.

### Plugin list:
-AsyncWorldEdit
-AutoDoor
-AutoPickup
-ChatColor
-ColoredSigns
-CS-CoreLib
-CustomScoreboard
-EchoPet
-EnjinMinecraftPlugin
-Esentials
-EZPrestige
-EZRanksLite
-iDisguise
-Multiverse-core
-Nicknamer
-PermissionsEx
-PlayerVaults
-PlotSquared
-PluginMetrics
-Plugman
-PrisonShops
-ProtocolLib
-Quicksell
-RainbowArmor
-Updater
-Vault
-WorldEdit
-WorldGuard

### Actions to reproduce (if known):
http://prntscr.com/boe8p0

### CratesPlus Version:
4.1.1

### CratesPlus config.yml
http://pastebin.com/Xpv6Djqx

### CratesPlus data.yml
http://pastebin.com/DicfvRTb

**Comment by ConnorLinfoot** [comment]
For holograms to work you need to install another plugin to handle it, either Holographic Displays or Individual Holograms.

As for configuration resetting this is caused by Bukkit when you input an invalid character or your YAML is invalid, the one you linked works fine and doesn't have issues for me. Make sure you don't put any invalid characters or make your YAML invalid (you can check it here http://yaml-online-parser.appspot.com)
