### ISSUE TITLE
Player's Can't open crates

### ISSUE THREAD

**Issue by SniperDanPro** [ConnorLinfoot/CratesPlus#317]
**Ok so I'm having trouble with players not being able to open the Crates with there keys unless there Opped is there any reason for this.**

(Plugins on my server)
WorldEdit, Survivalgames-Reloaded, PermissionsEX, ClearLag, Plugman, Vault, Mycommand, Hotpotato, Multiverse-Core. ProtocolLib, Skywars, Bedwars, BankNote, UltraCosmetics, Essentials, BlockHunt, EssentialsChat, SuperBuildBattle, Shop, Paintball, HolographicDisplays, EssentialsSpawn, CratesPlus, Crackshot,

Server Verison is 1.9.2

Please let me know if you want the IP and me to whitelist you so you can help me with CratesPlus =)

If you're having config issues (such as it resetting) first make sure it's a valid YAML file using a [parser](http://yaml-online-parser.appspot.com). Already Checked =)

From version 4.2 there is a new '/crates debug' command. Running this will give you a single link with all the data I need to help you. I've Done That
### Debug Link

**_Enter your debug link from /crates debug**_
https://mcdebug.xyz/cratesplus/1784

I hope someone can help me fix this problem =)

**Comment by Snoopyfun** [comment]
I've been having the same problem as well. ;-;

**Comment by Greenfoot5** [comment]
The problem is not the plugin or the permissions but the chest protection. I don't know wether permissionsEX changes any build perms but I use world guard and my players don'5 have permissions to build yet they can still open crates. If the crates are near spawn you can edit the server.properties and change the spawn protection but make sure any other plugins arn'5 stopping players from opening crates as well

**Comment by ConnorLinfoot** [comment]
Have you read the help on the wiki? https://github.com/ConnorLinfoot/CratesPlus/wiki/Debugging-Issues#players-cant-open-crates
