### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by Roadhog360** [ConnorLinfoot/CratesPlus#362]
1. Make it so the items in the crate gui can have a separate name/lore/itemstack than the item it gives. EG I can make it say Enchanted sword in the GUI but it does not give a sword with that name. Or I could have an item in the crate named 4 stacks of obsidian, and it'd show as 4 obsidian but gives 4 stacks of obsidian without a name.
2. Make a way to change the rolling GUI delay when using a key, and being able to turn it off as well. The GUI delay is massive.
3. Make it so when you win a reward, it can run commands instead of giving an item as well.
4. Make it so holograms, chance GUI name, etc can be different per crate.
5. Make the crate key name node and the crate colour node support raw colour codes like &c so I don't have to use the alt code and do §c instead.
6. If you change the hologram contents, this happens. You can't remove the holograms. They are stuck.[2017-03-27_22 00 15](https://cloud.githubusercontent.com/assets/11903511/24389956/6087834a-133a-11e7-8834-61b7f273f95e.png)

**Comment by ConnorLinfoot** [comment]
Probably be good if you check the [wiki](https://github.com/ConnorLinfoot/CratesPlus/wiki) next time

1. This is possible by using commands instead of items for the winnings, I don't plan adding a way to change this.

2. This already exists, check the opener configuration file.

3. This is already a feature, check the wiki.

4. This is already a feature, check the wiki.

5. Crate colors are managed via the color option, if you want to go deeper you have to use the § for that reason.

6. Hologram issues are acknowledged and depend on the library you're using
