### ISSUE TITLE
Change percentages to weights

### ISSUE THREAD

**Issue by GotoFinal** [ConnorLinfoot/CratesPlus#435]
it is pain to use as hell, imagine 40 crates, each with different chance....

You should add new `Weight` property and if it exist, then load it, if not then load old `Percentage`, as weighted random is much simpler to use, and much more accurate for such situations.

Or just change how you tract percentages, as you don't treat them as percentage anyway...
```java
      List<Winning> winnings = crate.getWinnings();
      
      double totalWeight = 0.0D;
      for (Winning winning1 : winnings) {
        totalWeight += winning1.getPercentage();
      }
      

      int randomIndex = -1;
      double random = Math.random() * totalWeight;
      for (int i = 0; i < winnings.size(); i++) {
        random -= ((Winning)winnings.get(i)).getPercentage();
        if (random <= 0.0D) {
          randomIndex = i;
          break;
        }
      }
```

So why limit it to 100%?

**Comment by GotoFinal** [comment]
not a answer I expected...

**Comment by kacperduras** [comment]
this is a real Hypixel developer @GotoFinal, you know nothing ( ͡° ͜ʖ ͡°)

**Comment by MrGregorix** [comment]
¯\_(ツ)_/¯

**Comment by insertt** [comment]
who cares ¯\_(ツ)_/¯

**Comment by ConnorLinfoot** [comment]
As a serious answer though the 100% requirement if I remember correctly is more of a legacy thing. When first created the percentage system worked differently rather than based on "weight" and it was required to have 100%.

It's likely possible to remove this limit but I never got round to testing it, it'll have a look when I get the chance moving forward with version 5.

In the past I've just told people to use decimals to make it easier if you want more than "100%", so instead of "10" for 10% just use 0.10 etc

**Comment by GotoFinal** [comment]
Yeach, with decimal should work fine, as you are using this as weight anyway, but with weird limit to 100.

**Comment by ConnorLinfoot** [comment]
Yes it should work as weights, as said the limit is just a legacy check that I'm 99.9% sure it can be removed :P
