### ISSUE TITLE
Issue with (/crate claim)

### ISSUE THREAD

**Issue by Kalcight** [ConnorLinfoot/CratesPlus#491]
When trying to remove keys from /crate claim they seem to be unmovable and will not transfer to the players inventory.

**Comment by Freya778** [comment]
I don't think you can remove items from crates, only when changing the items a crate can give out you can take an item out then. otherwise you can only get items out of them the normal way, when you use a key on it. You can get keys by rewarding them for voting or by giving them to players with a command.

**Comment by Kalcight** [comment]
You did not seem to read the question. When players vote and their inventory is full the keys get stored in a gui. You use /crate claim to get your keys but upon opening the gui it will not let you take them.

**Comment by ConnorLinfoot** [comment]
Please provide a debug link, will investigate further if provided.

**Comment by Kalcight** [comment]
https://mcdebug.xyz/cratesplus/share/nHuyCK34m4
